accounts/urls.py
from django.urls import path, include
from .views import signup_view, login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name="signup"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout")

]

apidev/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView, TokenRefreshView,)
from . import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'articles', views.ArticleViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls'))
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from .views import index_view, add_view, detail_view, delete, edit_view
urlpatterns = [
    path('', index_view, name='index'),
    path('add/', add_view, name='add'),
    path('detail/<int:id>', detail_view, name='detail'),
    path('delete/<int:id>', delete, name='delete'),
    path('edit/<int:id>', edit_view, name='edit')


]

djangodemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('articles.urls')),
    path('api/', include('apidev.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

apidev/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default='default.jpg', blank=True)

    def __str__(self):
        return self.title

    def truncate_snippet(self):
        return self.body[0:60] + '...'

articles/forms.py
from django import forms
from .models import Article
from django.contrib.auth.models import User


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'slug', 'body', 'thumbnail']

accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

apidev/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from articles.models import Article
from rest_framework import viewsets
from .serializers import UserSerializer, GroupSerializer, ArticleSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
# Create your views here.


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
# Create your views here.


class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

articles/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleForm
# Create your views here.


@login_required(login_url='/login/')
def index_view(request):
    articles = Article.objects.all()
    return render(request, 'index.html', {"articles": articles})


@login_required(login_url='/login/')
def add_view(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ArticleForm()
    return render(request, 'add.html', {'form': form})


@login_required(login_url='/login/')
def edit_view(request, id):
    article = Article.objects.get(id=id)
    if request.method == 'POST':
        article_id = get_object_or_404(Article, id=id)
        form = ArticleForm(
            request.POST, request.FILES, instance=article_id)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ArticleForm()
    return render(request, 'edit.html', {"article": article, 'form': form})


@login_required(login_url='/login/')
def detail_view(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'detail.html', {"article": article})


@login_required(login_url='/login/')
def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('index')

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1 class='text-center'>Login</h1>
    <form method="POST" class="form-wrapper">
        {% csrf_token %}
        <div class="form-group">
        <label for="id_username">Username:</label>
        <input type="text" name="username" required="" maxlength="254" id="id_username" autofocus="" class="form-control">
        </div>

        <div class="form-group">
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password" class="form-control">
        </div>
        
        <button class="btn btn-primary" type="submit">Login</button> 
    </form>
{% endblock content %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center p-3">Sign Up</h1>
    <form method="POST" class="form-wrapper">
        {% csrf_token %}
        <div class="form-group">
        <label for="id_username">Username:</label>
        <input type="text" name="username" required="" maxlength="150" id="id_username" autofocus="" class="form-control">
        </div>
        <label for="id_password1">Password:</label>
        <input type="password" name="password1" required id="id_password1" class="form-control">

        <label for="id_password2">Confirm Password:</label>
        <input type="password" name="password2" required id="id_password2" class="form-control">


        <button class="btn btn-primary p-2 mt-4" type="submit">SignUp</button>
    </form>
{% endblock content %}

articles/templates/add.html
{% extends 'base.html' %} {% block content %}

<div class="text-center p-2"><h2>Add Article</h2></div>

<form method="POST" class="form-wrapper" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="Title">Title</label
    ><input type="text" name="title" id="Title" class="form-control" />
     {% if form.title.errors %}
    <div class="alert-error" role="alert">
      {{ form.title.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-group">
    <label for="Slug">Slug</label
    ><input type="text" name="slug" id="Slug" class="form-control" />
    {% if form.slug.errors %}
    <div  role="alert">
      {{ form.slug.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-group">
    <label for="Body">Body</label>
    <textarea name="body" id="Body" class="form-control"></textarea>
  </div>
  <div class="form-group">
    <label for="Thumbnail">Add Thumbnail</label>
    <input type="file" class="form-control-file" id="Thumbnail" name="thumbnail">
  </div>
  <button class="btn btn-primary px-5 add-form-btn" type="submit">Add</button>
</form>
{% endblock %}

articles/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/favi.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>ArticlesDoc</title>
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="{% url 'index' %}">
          <img src="{% static 'images/logo.svg' %}" alt="logo" />
        </a>
      </div>
      {% if user.is_authenticated %}
      <div class="log-out">
        <form action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Logout</button>
        </form>
      </div>
      {% else %}
      <div>
        <a href="{% url 'accounts:login' %}" class="btn btn-success">Login</a>
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary">SignUp</a>
      </div>
      {% endif %}
    </header>
    {% block content %} {% endblock %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

articles/templates/detail.html
{% extends 'base.html' %} {% block content %}

<div class="text-center p-2 detail-title">
  <h2>{{ article.title }}</h2>
  <div class="btn-grp">
    <a href="{% url 'delete' id=article.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'edit' id=article.id %}" class="btn btn-success">edit</a>
  </div>
</div>
<div class="container">
  <div class="image-wrapper">
    <img src="{{ article.thumbnail.url }}" alt="Hero image" />
  </div>
  <div class="container-fluid bg-light content-detail">
    <div class="text-dark my-3">
      {{ article.date_added }}
    </div>
    <div class="text-body article-body">
      {{ article.body }}
    </div>
  </div>
</div>

{% endblock %}

articles/templates/edit.html
{% extends 'base.html' %} {% block content %}

<div class="text-center p-2"><h2>Edit Article</h2></div>
<form method="POST" class="form-wrapper" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
  
    <label for="Title">Title</label
    ><input
      type="text"
      name="title"
      id="Title"
      class="form-control"
      value="{{ article.title }}"
    />
    {% if form.title.errors %}
    <div class="alert-error" role="alert">
      {{ form.title.errors }}
    </div>
    {% endif %}
  </div>

  <div class="form-group">
    <label for="Slug">Slug</label
    ><input
      type="text"
      name="slug"
      id="Slug"
      class="form-control"
      value="{{ article.slug }}"
    />
    {% if form.slug.errors %}
    <div  role="alert">
      {{ form.slug.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-group">
    <label for="Body">Body</label>
    <textarea rows="4" cols="50" id="Body" class="form-control" name="body">
  {{ article.body }}</textarea
    >
  </div>
  <div class="form-group">
    <label for="Thumbnail01">Edit Thumbnail</label>
    <input type="file" class="form-control-file" id="Thumbnail01" name="thumbnail" value="{{ article.thumbnail.url }}">

  </div>
  <button class="btn btn-primary px-5" type="submit">Edit</button>
</form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %} {% block content %}

<div class="title-section">
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'add' %}"
    ><button class="btn btn-primary add-btn">Add</button></a
  >
</div>

<div class="d-flex flex-wrap listing-articles">
  {% for article in articles %}
  <div class="card m-2 card-wrapper" style="width: 18rem;">
    <div class="card-body">
      <a href="{% url 'detail' id=article.id %}"
        ><h5 class="card-title">{{ article.title }}</h5></a
      >
      <h6 class="card-subtitle mb-2 text-muted">{{ article.date_added }}</h6>
      <p class="card-text card-desc">
        {{ article.truncate_snippet }}
      </p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}